# Generated by Django 4.1 on 2022-09-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catwiseitems',
            name='cat',
            field=models.CharField(choices=[('electronics', '1'), ('cloths', '2'), ('kids', '3'), ('kitchen', '4'), ('cat', '5')], default='electronics', max_length=100),
        ),
        migrations.AlterField(
            model_name='catwiseitems',
            name='image',
            field=models.ImageField(upload_to='shop/'),
        ),
    ]
