# Generated by Django 4.1 on 2022-09-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_catlist_category_name_alter_catwiseitems_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catlist',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
