# Generated by Django 4.1 on 2022-09-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_catlist_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catwiseitems',
            name='long_discription',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='catwiseitems',
            name='short_discription',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='catwiseitems',
            name='specs',
            field=models.TextField(max_length=100),
        ),
    ]
