# Generated by Django 4.1 on 2022-09-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_catwiseitems_long_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catlist',
            name='category_name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
