# Generated by Django 4.1 on 2022-10-09 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
