# Generated by Django 4.1 on 2022-10-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=255)),
                ('contact_no', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
