# Generated by Django 4.1 on 2022-10-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_contactus_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactus_form',
            new_name='contactus',
        ),
    ]
