# Generated by Django 4.1 on 2022-10-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_cart_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='quantity',
        ),
    ]
