# Generated by Django 4.1 on 2022-10-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='order_total',
        ),
    ]
