# Generated by Django 4.1 on 2022-09-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0002_rename_book_uploaded_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaded_file',
            old_name='title',
            new_name='file_name',
        ),
    ]
