# Generated by Django 4.1 on 2022-09-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0003_rename_title_uploaded_file_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploaded_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='image')),
            ],
        ),
        migrations.AlterField(
            model_name='uploaded_file',
            name='pdf',
            field=models.FileField(upload_to='upld'),
        ),
    ]
