# Generated by Django 4.1 on 2022-09-06 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0004_uploaded_image_alter_uploaded_file_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded_image',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
