# Generated by Django 4.1 on 2022-09-06 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0006_uploaded_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_image',
            name='upload_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 6, 16, 5, 50, 21388)),
        ),
    ]
