# Generated by Django 4.1 on 2022-09-06 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0007_alter_uploaded_image_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_image',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2022, 9, 6, 21, 43, 30, 338208)),
        ),
    ]
