# Generated by Django 4.1 on 2022-09-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0008_alter_uploaded_image_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_image',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
