# Generated by Django 4.1 on 2022-09-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0014_alter_uploaded_image_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded_image',
            name='author',
            field=models.CharField(default=0.26136363636363635, max_length=20),
            preserve_default=False,
        ),
    ]
