# Generated by Django 4.1 on 2022-09-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0015_uploaded_image_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaded_image',
            name='author',
        ),
    ]
